baseURL = "https://kukode.in/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Kukode.in - Jasa Bikin Website & Maintenance Website Profesional"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About Us"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "faq"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "privacy-policy"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "blog"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "© Copyright 2020 • Kukode.in - Jasa Bikin Website & Maintenance Website"
footerLogo = "images/site-navigation/logo_white.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "U-000000-1"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Perumahan Kepuh Permai, Jl. Kepuh Permai No.D35, RT.05/RW.23, Gondang Legi, Wedomartani, Ngemplak, Sleman Regency, Special Region of Yogyakarta 55548."
email = "kukodein@gmail.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+62 877-2626-5660"

[params.map]
APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/kukodein"
weight = 1
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/kukode.in"
weight = 2
[[params.social]]
icon = "fa-telegram"
url = "https://t.me/kukodein"
weight = 3
[[params.social]]
icon = "fa-whatsapp"
url = "https://api.whatsapp.com/send?phone=6287726265660"
weight = 4
[[params.social]]
icon = "fa-github"
url = "https://github.com/kukodein"
weight = 5
